### ISSUE TITLE
The screen icons use a different font than the screens

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#114]
Discovered in #99: Screen icon:

![image](https://user-images.githubusercontent.com/679486/38772984-641945a4-4000-11e8-9dab-254395643c62.png)

Screen:

![image](https://user-images.githubusercontent.com/679486/38772991-7dc12120-4000-11e8-871f-c7c6d90cd0d5.png)

The inconsistency somewhat surprised me and I couldn't think of a good reason for it (though I bet there is a good reason for it.) So I thought I'd ask.

**Comment by amanda-phet** [comment]
Here is the reason: https://github.com/phetsims/area-model-common/issues/97#issuecomment-379836035

We designed the icons to be simplifications, and for the other screens what you see in the icon doesn't match what you can see in the sim. Rather, it represents what you would see when working with pencil and paper. The Explore screen was the only one using the sim font, so we changed it to be more consistent across all screen icons. 

@samreid you only pasted the example from the Explore screen. Do you think the other screen icons look strange for using a different font, or is it just this one?

**Comment by jonathanolson** [comment]
The different font felt aesthetically jarring to me personally, but I don't have strong feelings. It seems there are reasons we would use that font instead of something that would match the sim?

**Comment by samreid** [comment]
> Do you think the other screen icons look strange for using a different font, or is it just this one?

At the moment, all of the screen icons are consistent with each other but inconsistent with the rest of the simulation.  They all look strange because none of them match the rest of the simulation.  If the "playful" font is important enough to use on the home screen icons, why not use it throughout the sim?If there are reasons to use the standard font in the sim screens, why don't those reasons apply to the homescreen?

**Comment by amanda-phet** [comment]
Current Generic screen icon:
![image](https://user-images.githubusercontent.com/7852916/38825682-be5626fc-416a-11e8-9786-7fe36f56dd2f.png)


Same concept, but using Arial font: 

![image](https://user-images.githubusercontent.com/7852916/38825628-8bc9694c-416a-11e8-8837-6e4ac15f34f6.png)

This just looks dull and less aesthetically pleasing to me. It would achieve the same goal of allowing users to differentiate between screens, because the content is the same. But I wonder if this is also strange because the icon is closer to actual appearance of the sim but still does not mimic something you can actually do in the sim. The other one seems obvious to me that you can't replicate using the sim. 

This is how the sim displays the same information:
![image](https://user-images.githubusercontent.com/7852916/38825842-28e0707c-416b-11e8-8c36-2cee86e09b2d.png)


I find the font issue most troubling on the Explore screen icon, but very strongly prefer the other icons. They are simple, clear, and pretty. However I don't want to make a decision that is nonsensical to other PhET team members, so I'm happy to discuss this again with Ariel and Kathy.

**Comment by amanda-phet** [comment]
Updated the icons to match the PhET font. @samreid can you see if these look reasonable to you?

**Comment by jonathanolson** [comment]
NOTE: Don't close this issue without me. I'll need to include any changes manually in the branched sims.

**Comment by samreid** [comment]
They look great to me, thanks!

**Comment by amanda-phet** [comment]
Nope!
