### ISSUE TITLE
Consider a common suffix for enums?

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#117]
During #99 I noticed the following enums:

DisplayType
GameState
Field
PartialProductsChoice
InputMethod
AreaCalculationChoice
Highlight
Orientation
GenericLayout
PartitionLineChoice
AreaChallengeType

Orientation is a richer-enum, Field has a method, etc.

Have you considered ending all of these with the same suffix, such as `Type`? or `Enum` or `Choice`? I was wondering if that would make it easier for maintainers to follow.  Let's discuss before making any changes.

**Comment by jonathanolson** [comment]
Since we have the "line length" limitations (and for conciseness), I'd be adverse to increasing the length of the name of something like Orientation. It's something commonly used in the sim, so I think a short understandable name should be a priority.

For basically everything else, I'm fine with whatever length name helps. "Type" doesn't make sense for GenericLayout/Orientation, "Choice" doesn't make sense for Field, and "Enum" to me doesn't add a lot of information. However I feel like "Highlight" and "Field" in particular are definitely suboptimal names, and I'd like to hear suggestions in general for everything.

**Comment by jonathanolson** [comment]
Tagging for developer meeting to see if we should have a common suffix for enumerations (I'd like to hear the argument for them, but I currently don't see the benefit).

**Comment by jonathanolson** [comment]
> Also maybe change, Highlight.js to FieldFocus.js or FieldStatus.js. I don't have a good suggestion for Field.js, maybe Entry.js.

What do you think about Field => EntryType, Highlight => EntryStatus?

**Comment by samreid** [comment]
That sounds nice.

**Comment by jonathanolson** [comment]
The above naming changes were implemented above. I'll be doing similar work in https://github.com/phetsims/area-model-common/issues/123. Let me know if there is further discussion/implementation that should be done for this issue.

**Comment by samreid** [comment]
After this discussion, I'm convinced we do not need to enforce a suffix for enums.  @jonathanolson is there anything else to discuss?  Can this issue be unmarked for developer meeting and closed?

**Comment by jonathanolson** [comment]
Unmarked and closing.
