### ISSUE TITLE
Are these overlapping touch areas OK?

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#125]
I noticed these overlapping touch areas during #99:
![image](https://user-images.githubusercontent.com/679486/38907268-558050e4-4278-11e8-82dd-90a7fb074dfb.png)

If I understand correctly, for the overlaps, whichever node has the highest z-index will catch the event.  I'm not sure which node that is for this case.

**Comment by samreid** [comment]
Also, why are the partition handles touch areas at an angle?
![image](https://user-images.githubusercontent.com/679486/38907321-976dba50-4278-11e8-9802-06ab81fb6e8d.png)

**Comment by samreid** [comment]
I guess that helps a bit with opening up the top-left of the drag circle in this extreme case.

**Comment by jonathanolson** [comment]
> If I understand correctly, for the overlaps, whichever node has the highest z-index will catch the event. I'm not sure which node that is for this case.

Yup. I believe I asked and was told that it wouldn't matter if you clicked at the crossing and your mouse was technically slightly closer to the bottom one (but it selected the top one).

> Also, why are the partition handles touch areas at an angle?

Somewhat ironically, given the name of this issue, to prevent overlap in this case: https://github.com/phetsims/area-model-common/issues/80#issuecomment-366076149 between the two handles, since it was possible to design areas between the two that would never overlap.

**Comment by amanda-phet** [comment]
It sounds like @jonathanolson has handled the overlapping areas well. 

And yes the angle is for the extreme case when the two handles are close.

**Comment by samreid** [comment]
It seems this is working as desired, closing.
