### ISSUE TITLE
Factor out EPSILON

### ISSUE THREAD

**Issue by samreid** [phetsims/area-model-common#156]
From #99, the simulation has this code, in 3 files:

```js
return Math.abs( this.coefficient - term.coefficient ) < 1e-7 && this.power === term.power;
```

```js
return totalSize >= ( self.partitionSnapSize + self.snapSize ) - 1e-7;
```

```js
if ( Math.abs( value - Util.roundSymmetric( value ) ) < 1e-6 ) {
```

Is there a reason that a 1e-6 is used instead of 1e-7 in the latter case?  Can we factor out the occurrences to a constants file, naming it something like `EPSILON` and adding brief documentation?

**Comment by jonathanolson** [comment]
> Or maybe create and use dot.Util.approxEquals() which defaults to an (overrideable) epsilon of 1E-7?

We have `Util.equalsEpsilon()`.

> Is there a reason that a 1e-6 is used instead of 1e-7 in the latter case? Can we factor out the occurrences to a constants file, naming it something like EPSILON and adding brief documentation?

They are fundamentally values with different usage, that in general should NOT change together, so refactoring them to one common epsilon would create more difficult code. "Fixing" the epsilon to solve one problem could then create another.

> Also, I noticed that Javascript already has a constant for its own machine epsilon:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON

Snazzy, I'll need to remember that. We actually get floating-point error that could potentially be larger (since we use larger numbers than 1) so I probably can't use that directly.

**Comment by samreid** [comment]
For this issue, I recommend to `Util.equalsEpilon()` and for each occurrence, comment that the epsilon values should differ from each other, and how you arrived at the epsilon values.

**Comment by jonathanolson** [comment]
> I recommend to Util.equalsEpilon() and for each occurrence

This only applies to the first case, correct?

**Comment by samreid** [comment]
Maybe 1st and 3rd case?

**Comment by jonathanolson** [comment]
> Maybe 1st and 3rd case?

Yup, my bad. Implementing.

**Comment by jonathanolson** [comment]
Changes made, can you see if there's something I should improve?

**Comment by samreid** [comment]
Looks great, thanks! Closing.
