### ISSUE TITLE
Possible Memory leak issues.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-common#199]
During the memory tests for https://github.com/phetsims/qa/issues/1059 and https://github.com/phetsims/qa/issues/1058, I noticed a possible memory leak. It was worse in Area Model Decimals.
Memory test for Decimals:
<img width="348" alt="decmem" src="https://github.com/phetsims/area-model-common/assets/41024075/ea117501-e6c2-4c88-b666-b841a6a47906">
Memory test for Introduction:
<img width="347" alt="intmem" src="https://github.com/phetsims/area-model-common/assets/41024075/e415ffd6-7887-4522-8d28-d3d6593e48b0">

**Comment by jessegreenberg** [comment]
I did memory testing on my windows 10 laptop and saw this memory profile over ~15 minutes of fuzzing.

![image (2)](https://github.com/phetsims/area-model-common/assets/6396244/11284196-4922-4264-8920-3664109c956d)

**Comment by Luisav1** [comment]
@marlitas did some memory testing on main for both AMI and AMD, yielding results that indicate this is not an issue on main.
![image](https://github.com/phetsims/area-model-common/assets/52978048/e93ab238-5cf9-4f70-bda2-bbcbe2bd5c17)
![image](https://github.com/phetsims/area-model-common/assets/52978048/e403e7db-d9c7-435f-ad11-b3615dee73f7)

Additionally, @marlitas also tested their respective RC versions. We're confident that there's no leak in AMI with the following results, but we're less certain about AMD. However, with @jessegreenberg's test results above, it seems increasingly unlikely that there's a leak in AMD as well.
![image](https://github.com/phetsims/area-model-common/assets/52978048/cfef09eb-1917-4ec1-b744-24541a9adce7)

@jonathanolson, as you're the responsible dev, would you like to weigh in that these results also look good to you?

**Comment by jonathanolson** [comment]
Those results look acceptable to me!

**Comment by KatieWoe** [comment]
My test for AMD looked rather different, and seemed ok. Not sure why we see difference here.
![decimals](https://github.com/phetsims/area-model-common/assets/41024075/4743b56d-5240-438e-897e-d5a697a18fda)
Introduction was a bit more iffy, but mostly seemed ok.
![introduction](https://github.com/phetsims/area-model-common/assets/41024075/be84663a-4992-463f-b2df-d0d1152bc6f7)

**Comment by Nancy-Salpepi** [comment]
Ugh! That is really weird--yours looks much better! I can try again....

**Comment by Nancy-Salpepi** [comment]
same as last time....I included the sim title in the screenshot so I am positive I didn't mix them up...
Could there be a difference between Mac and Windows??

<img width="351" alt="Screenshot 2024-04-12 at 4 55 48 PM" src="https://github.com/phetsims/area-model-common/assets/87318828/2e5b3ab7-4b0e-40d4-b064-e802c7489136">

**Comment by jonathanolson** [comment]
Feel free to include me, especially if things are looking platform-specific. Are there steps I can take to get this reproducing?

**Comment by Nancy-Salpepi** [comment]
@jonathanolson I'm following the steps in the QA book for Memory Leak Testing--
https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#47-memory-leak-testing

**Comment by Luisav1** [comment]
I conducted some additional memory tests for AMD following the outlined procedure, with a minute between each snapshot and a 10-minute interval between snapshot 11 and 12.

In the main branch:
![image](https://github.com/phetsims/area-model-common/assets/52978048/61e49343-0888-4905-b279-38fa39e8972d)

The 1.3 rc.2 version:
![image](https://github.com/phetsims/area-model-common/assets/52978048/e7ab1904-1095-4290-833e-55028c07b038)

As well as the 1.3 branch with its SHAs checked out:
![image](https://github.com/phetsims/area-model-common/assets/52978048/5ecb55b3-cf6b-414b-9eb5-f86ecc7b0ed4)

A potential memory leak appears in 1.3, though minor. No apparent issue exists in the main branch. During today's stand-up, @marlitas and I discussed the differences between Mac and Windows environments, confirming Nancy's earlier suggestion. Users on Macs (@marlitas, @Nancy-Salpepi) reported observing something, while those on Windows (@jessegreenberg, @KatieWoe, @Luisav1) didn't notice such a clear leak. This suggests the memory leak may indeed be platform-specific.

**Comment by jbphet** [comment]
@jonathanolson hasn't been available, so @Luisav1 and I decided to take a look at this together.  We ran a test where we fuzzed for a while in a Chrome incognito tab on my Win 11 machine and say leakage at approximately 3.5 MB per minute.  Through examining the memory trace, we found two things that warrant further examination:

- There are a lot of RichDragListener instances being created and disposed, and each time this happens new instances of SoundClip are being created and registered with the soundManager, but these are never being disposed, so that is causing some of the leakage.  When we commented out the addition of these clips, the leak rate went down by about 1/2.
- There are also a lot of `Function` instances being created and not removed that are associated with `partitionSplitVisibleProperties`.  Here is a screenshot:
  ![image](https://github.com/phetsims/area-model-common/assets/3082831/ef5b3222-fba8-4212-a66a-1e36ed473c58)

I'll investigate the first of these, and @Luisav1 will look into the second, and we will go from there.

**Comment by jbphet** [comment]
I did some more investigation and found that instances of `SoundClip` were indeed leaking, but not because they weren't being disposed by `RichDragListener`.  `RichDragListener` is disposing the `SoundClip` instances as it should, but `SoundClip` itself had an issue where, if disposed before the audio context ever became active, a listener that was registered with `audioContextStateChangeMonitor` was not being removed.  I've fixed this.  In my fuzz testing before this fix I saw a delta of +576 `SoundClip` instances.  After the fix there were none.  The memory leak rate went from 4.8 MB/min to 0.7 MB/min, though this was only a single before-and-after test.

The thing that is unusual about this sim that caused it to be the first to run into this problem is that sound is disabled, but sounds are being created and disposed frequently during fuzz testing since the code is creating and disposing a lot of `RichDragListener` instances, which (as of fairly recently) include sound by default.

@Luisav1 - The situation for this sim should improve if you incorporate the commit above.  I think my part is now done.

**Comment by Luisav1** [comment]
I found two listeners on the `partitionSplitVisibleProperty` which are never disposed. However, these listeners are added within `ProportionalPartitionLineNode`, which is designed to persist in the simulation. Therefore, it seems that unlinking them may not be necessary.

I conducted tests before and after commenting out one of the listener functions, specifically:
```js
areaDisplay.partitionSplitVisibleProperties.get( orientation ).link( visible => {
        !visible && dragHandler.interrupt();
      } );
```
Surprisingly, the number of `Function` instances remained similar in both cases. Although during my tests, I couldn't detect any `Function` instances associated with `partitionSplitVisibleProperty`.

Nonetheless, the test on the AMD main branch shows a significant reduction in the leak. There's a 10-minute gap between Snapshot 10 and 11.
![image](https://github.com/phetsims/area-model-common/assets/52978048/86e76e44-216a-47e1-b038-100cd0230704)
I plan to test the 1.3 branch after patching the tambo commit to determine if the improvement persists.

**Comment by Luisav1** [comment]
After applying the commit to the AMD and AMI 1.3 branches and running memory tests, it seems the leak is also gone from AMD. See test results below:
![image](https://github.com/phetsims/area-model-common/assets/52978048/0eeb29d7-2ff2-4767-8d55-388f2717f9d8)

Leaving this issue open to be reviewed by QA in the next spot check.

**Comment by Nancy-Salpepi** [comment]
Memory Test results look good to me. 

AMD 1.3.0-rc.2 (with 10 minutes between shots 10-11):
<img width="228" alt="Screenshot 2024-04-25 at 5 16 08 PM" src="https://github.com/phetsims/area-model-common/assets/87318828/959b80cd-8e80-4462-af40-27441dfc76b9">

I also took a look at AMI (with 10 minutes between shots 10-11): 
<img width="228" alt="Screenshot 2024-04-25 at 4 51 48 PM" src="https://github.com/phetsims/area-model-common/assets/87318828/28f4de4c-6c80-4704-b33a-fe047460939d">

**Comment by KatieWoe** [comment]
AMD on Win 11 Chrome
![decmem](https://github.com/phetsims/area-model-common/assets/41024075/50222e42-228e-4d7e-b82f-5c08f3879eef)
AMI on Win 11 Chrome
![intromem](https://github.com/phetsims/area-model-common/assets/41024075/ecaa0bf2-0c59-4cdf-a19f-64f1bf70ee49)
