### ISSUE TITLE
Readout/edit size for right side when allowing exponents

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#22]
The readout/label doesn't fully fit inside the ideal area for it, so it looks a bit ugly:
![screen shot 2017-05-16 at 1 29 11 pm](https://cloud.githubusercontent.com/assets/480878/26124473/c6e96b9e-3a3b-11e7-8adf-adf36c6dc30a.png)

@amyh-phet thoughts on how to resolve? I didn't want to make the partitions too equal in size on the 3rd screen, but that could resolve it. I could also reduce padding/sizes some.

**Comment by amyh-phet** [comment]
I agree that we don't want the partitions to be too equal in size on the 2nd or 3rd screen.  We could make the first partition a bit smaller so that we can move the 2nd and 3rd partitions over, making the 3rd partition slightly larger.  

Not sure we want to remove too much padding, but we could try reducing the size (I'm assuming font size too?) a bit to see if that helps.

**Comment by jonathanolson** [comment]
Slightly changed partition sizes, does this look good enough:
![screen shot 2017-05-16 at 2 36 14 pm](https://cloud.githubusercontent.com/assets/480878/26127025/113d2114-3a45-11e7-9bb5-785e35dd2149.png)

**Comment by amyh-phet** [comment]
Looks good - much better with adjustments you made.

**Comment by jonathanolson** [comment]
Thanks, closing.
