### ISSUE TITLE
How to handle() a PushButton event?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#35]
Ideally, I want a RectangularPushButton to call handle() on the Scenery event when the listener is fired, so that it won't trigger listeners underneath.

Is there a convenient way to access the Scenery event from the listener callback, or should I rely (in this case) on the fact that my "button operation" is idempotent?

**Comment by jbphet** [comment]
There isn't currently a convenient way to access the Scenery event from the listener callback.  I just looked through the code, and it doesn't seem like it would be trivial to make the event available due to the decoupling between the listener and the button model.

It seems to me like it's a very rare case where we *wouldn't* want a button to fully handle a Scenery event, so one possibility would be to make the button listener always do so.  I'm reasonably confident that we don't have cases where buttons are on top of things that are also listening for events and counting on said events to be received 'through' the button, but we should check in with other developers if we decide to consider this solution.

Another possibility would be to add an option that would control whether `handle()` is called on the received input events, e.g. `handleInputEvents`, and propagate it as necessary through the collection of objects that implement the button behavior.

@jonathanolson - you said,
> [S]hould I rely (in this case) on the fact that my "button operation" is idempotent?

I looked up 'idempotent', but I'm still not sure what you mean by this, so I can't really respond to this portion of your question.

**Comment by jonathanolson** [comment]
> I'm reasonably confident that we don't have cases where buttons are on top of things that are also listening for events and counting on said events to be received 'through' the button

I believe the effect that closes combo boxes for clicks outside does this, where a listener is added way above. Calling `handle()` would be undesirable in that case (which is actually the case in this sim now that I think about it).

> my "button operation" is idempotent?

"Running the action more than once has the same effect as running it more than once. Only the first run would cause an actual change". So basically the second "button press" that activates in my case would try to set a property to the value that is already set, which would be ignored.

It sounds very tricky to add `handle()` in general or for this specific case, so I'd almost prefer not to do so. Really what we would want is something stored on the event that it "did something" but still allows it to propagate.

@jbphet, assigning to you for your thoughts. I'm fine to bail on this and close if you are.

**Comment by jbphet** [comment]
@jonathanolson - this issue has been languishing for a couple of years now.  It doesn't seem to have come up as something that is needed, since the priority has never been elevated and I don't recall any conversations requesting this feature.  You said you were okay to close if I was, and I am, but mostly because I don't know exactly what to do to address the issue and don't feel like it's worth the time to dive into it.  Over to you for one last look and closure if you're good with that.

**Comment by marlitas** [comment]
It sounds like the decision in 2019 was to close this and nothing else has moved forward here so I'm going to go ahead and close. Feel free to re-open if someone feels otherwise.
