### ISSUE TITLE
Add valueToString function option to NumberPicker

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#5]
@pixelzoom, any objections for me to add a function that controls how to convert the given value to a string?

We need to display a '1' for 1, but '0.5' for 0.5 (which won't work with toFixed).

Presumably if that option is given, we'll need to iterate over all possible picker values to determine the maximum dimensions of the value node (instead of checking min/max like is done now).

**Comment by pixelzoom** [comment]
Looks like @samreid added something similar in https://github.com/phetsims/scenery-phet/commit/124a6a033406e8addd6a09cb1a0608e148581dda#diff-554e2c2e53928cb5c370b1799c9afbf0:

```js
formatText: function( text ) {return text;}, // Text processor that can be used for formatting the text
```

Inadequately documented, but it looks like the type expression is `{function(string):string}`.

Will this work for you?

**Comment by pixelzoom** [comment]
Actually, I guess that won't really work for you.  Too bad something like `formatValue` wasn't added, `{function(number):string`.  Maybe change?

**Comment by jonathanolson** [comment]
Changing to formatValue would be great, I can take care of refactoring usages.

**Comment by pixelzoom** [comment]
Not sure what effect `formatValue` might have on `options.decimalPlaces` - does it make it irrelevant?

**Comment by jonathanolson** [comment]
No, presumably the default formatValue would use decimalPlaces (so we don't require formatValue for every NumberPicker).

**Comment by jonathanolson** [comment]
Applied changes, but it looks like https://github.com/phetsims/scenery-phet/issues/306 is an issue (bounds only set at the start, not modified with range changes). Didn't handle that.

@pixelzoom, can you review?

@jessegreenberg, can you review https://github.com/phetsims/gravity-force-lab-basics/commit/145010e14472bab4a7c7af202fe897ae03b6189e (change to your sim) to make sure I didn't break anything? Wasn't sure how to test.

**Comment by pixelzoom** [comment]
Looks OK, but a question about https://github.com/phetsims/scenery-phet/commit/270d150e7dd32c714acc512ef4b9c0aade2a6a95.  Computing the width now involves computing every possible value.  Do you anticipate that that may cause performance problems?

**Comment by jonathanolson** [comment]
> Do you anticipate that that may cause performance problems?

There's the potential for that, although I'm not sure of a good other way to do that. (It also fails if you reverse upFunction/downFunction so that it never reaches the max, or a few other ugly edge cases that we probably won't run across).

If I have a range from 0 to 1 ("0" and "1") that goes through and "0.8" is the widest value, how else would we find that?

**Comment by pixelzoom** [comment]
Indeed, with the addition of `options.formatValue`, we have no choice but to compute all values to determine the width.   

So trying to compute the dimensions is problematic for a number of reasons... `formatValue`, mutable range,...  How about if change the API, so that the client is responsible for setting the dimensions, then scale whatever value is displayed to fit?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/gravity-force-lab-basics/commit/145010e14472bab4a7c7af202fe897ae03b6189e works great, thanks @jonathanolson.

The API suggestion in https://github.com/phetsims/area-model-common/issues/5#issuecomment-301915660 sounds like a good solution to me.

**Comment by jonathanolson** [comment]
> How about if we change the API, so that the client is responsible for setting the dimensions, then scale whatever value is displayed to fit?

Sounds inconvenient for every client to decide on the bounds required? And then have to re-supply NumberPicker with different bounds when the Range changes?

So I need to refactor so I can grab the default font (or override, but use the same values), so I can (on NumberPicker construction and every time the range changes) iterate through all possible values, map those values with whatever formatValue is (or again, make changes to get the default), determine the maximum dimensions, and potentially have to reconstruct NumberPicker with the new bounds (since NumberPicker assumes bounds don't change)? And I'll need to do at least part of that every place NumberPicker is used?

**Comment by pixelzoom** [comment]
I'll be surprised if the design team is happy with a picker whose width keeps changing.  Can you initialize NumberPicker with the largest range (i.e. widest picker) that you're likely to need?

**Comment by pixelzoom** [comment]
Since this issue is in area-multiplication, I'm guessing that the context is the Product accordion box, and the range change is when you switch between the "20 x 20" and "100 x 100" scene.  

Imo, this definitely does not justify the complexity of making NumberPicker change its width when the range changes.

Imo, you should not be using the same NumberPicker for both scene.  But if you must, initialize the NumberPicker with the larger of the ranges.  Or live with the "100" value scaling down, which doesn't look bad imo.

**Comment by pixelzoom** [comment]
Since this issue is in area-multiplication, I'm guessing that the context is the Product accordion box, and the range change is when you switch between the "20 x 20" and "100 x 100" scene.

Imo, this definitely does not justify the complexity of making NumberPicker change its width when the range changes.

Imo, you should not be using the same NumberPicker for both scene - making UI components mutable introduces exactly this kind of complexity. But if you must, then initialize the NumberPicker with the larger of the ranges. Or live with the "100" value scaling down, which doesn't look bad imo.

**Comment by jonathanolson** [comment]
Discussed with @pixelzoom, decided that passing in the maximum range first should handle sizing for range changes nicely (big enough to fit them all). Added documentation, closing.
