### ISSUE TITLE
Distinguish negative and minus signs

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#65]
Minus signs (indicating subtraction) should use the unicode "–" symbol and negative signs should just be "-" symbols. 

All of the circled signs in the screenshot below should be minus signs.  
![screen shot 2017-06-20 at 2 54 21 pm](https://user-images.githubusercontent.com/7852916/27355503-7c8b4aba-55c8-11e7-9bf9-e734cf81282a.png)

This is a common convention that makes the symbols easier to parse. If it is not possible, or is very difficult, we should use the unicode symbol in all instances as it is much easier to read than the short negative sign.

**Comment by amyh-phet** [comment]
@jonathanolson   Hopefully this change isn't too difficult to implement.

**Comment by jonathanolson** [comment]
Implemented, however instead of "–" (Unicode EN DASH \u2013) did you mean "−" (Unicode MINUS SIGN \u2212)? Notably, the minus and plus signs are about the same level (seems visually high), but the en dash is vertically lower.

Other common code seems to use the minus sign instead of the en dash.

Comparisons:

Minus sign:
![area-minus](https://user-images.githubusercontent.com/480878/27364734-87a75a5c-55f9-11e7-9451-cabe5706e751.PNG)



En dash:
![area-em-dash](https://user-images.githubusercontent.com/480878/27364738-91990830-55f9-11e7-9e64-5dddea07b18c.PNG)

**Comment by amanda-phet** [comment]
The unicode minus sign looks like the correct one.

**Comment by jonathanolson** [comment]
I believe this is completed, let me know if it looks good?

**Comment by amanda-phet** [comment]
Looks great. Thanks!
