### ISSUE TITLE
Should the erase button be disabled sometimes?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#77]
The basics/counting design doc noted:

> Erase button is grayed out and inactive.

for its initial conditions.

Currently, the erase button isn't disabled on any screen, but it definitely could be:

- For proportional (Explore, Decimals, Counting) screens, it could be disabled whenever the active area is at the default (and if it has partitions, if those are also at the default).
- For generic (Generic, Variables) screens, it could be disabled whenever no partition has any value set.

Thoughts?

**Comment by amanda-phet** [comment]
I have some thoughts... 

I find it strange that the erase button returns the board to the starting state. I would expect "erase" to clear any settings in the board. 

So, instead of starting with the button disabled, perhaps it should start enabled, and when pressed, it resets the model to a 1x1 square (for Explore, Decimals, Multiplication, and Partition screens- all screens with proportional models).

**Comment by amanda-phet** [comment]
I discussed this with @kathy-phet and since the sim has changed quite a bit since the button's initial design, we'd like to move forward with my suggestion above: 

The button is never disabled. 

When pressed, the current model returns to a 1x1 square (Explore, Decimals, Multiply, Partition screens) or clears the model (Generic, Variables screens).

Can you please implement this before Friday so we can get this change in the next dev version for interviews?

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by amanda-phet** [comment]
This is working on all sims, but there are a few funny things.. 

On 100x100 boards, 1x1 is extremely tiny. I wonder if we should consider going to 10x10 in those cases (the Explore screen on Multiplication and Algebra). 
<img width="406" alt="screen shot 2018-02-09 at 9 59 49 am" src="https://user-images.githubusercontent.com/7852916/36039580-2021af60-0d80-11e8-86ba-21ac34e3d5a5.png">


On the 1x1 decimals board, the entire board ends up being filled! And the partition lines remain wherever they are. I think we should consider going to 0.1x0.1.
<img width="440" alt="screen shot 2018-02-09 at 10 00 15 am" src="https://user-images.githubusercontent.com/7852916/36039573-1add3bd2-0d80-11e8-832a-bcfcea68ec48.png">


Having the erase button behave differently might seem odd, but in fact all of these "cleared" states are the largest square you can make before a partition line appears, so it really feels like it clears your work. They are also simply the top left grid square (which changes based on the scale). 

<img width="416" alt="screen shot 2018-02-09 at 9 59 58 am" src="https://user-images.githubusercontent.com/7852916/36039592-28394e06-0d80-11e8-86c4-d0d155700f78.png">
<img width="433" alt="screen shot 2018-02-09 at 10 00 22 am" src="https://user-images.githubusercontent.com/7852916/36039602-2d752d9a-0d80-11e8-80e2-83391d7d97b7.png">


So, can we: 
* change the 100x100 board in both the Multiplication and Algebra sims to reset to 10x10 when erase is pressed
* change the 1x1, 2x2, and 3x3 boards in the Decimals sim to reset to 0.1x0.1

**Comment by kathy-phet** [comment]
I like this suggestion too.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by amanda-phet** [comment]
This looks good to me. Thanks!
