### ISSUE TITLE
On the Partition/Explore Screens: Have Partial Product "A" view on by default

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/area-model-common#83]
As I have been playing with this simulation, I am feeling like it would be a better learner/explorer experience to start with the partial products on (the "A" view). Right now the feedback they get as they play with the partitions isn't much - just seeing the divisions on the side change. And the total area readout is not where you are looking when you changing things in the square. So I would like to advocate for considering having the partial products visible as the default on this screen. They are providing very powerful feedback as you change the partition and as you change the area - and could motivate more of a puzzle/challenge to figure them out and what they are doing if they are on. In my "interviews" of my nieces, they did not find that control to turn them on for quite a while and were not really engaging in the sense making I was looking for, and when they did turn them on, they didn't really see how powerful they were and just cycled through the views and turned them back off, partially I think because they could not see that they were dynamic because they could not both turn them on and be playing with the shape/partition at the same time. 

Thoughts?

**Comment by kathy-phet** [comment]
@amanda-phet: Just pinging you here so you see this suggestion.

**Comment by amanda-phet** [comment]
My thought was that we should start with partial products off so that students could focus on the divisions first. It could be a lot to process if it's the first time someone sees partitions, especially coming from the previous screen which only counts boxes. 

Since I'm interviewing next week, would you like me to try both options in front of different students?

**Comment by amanda-phet** [comment]
How old are your nieces?

**Comment by kathy-phet** [comment]
Yes, please try each way. I'm concerned that division of the side only doesn't really provide the student with much feedback on what has actually changed in terms of how to think about the problem. 

Perhaps @jonathanolson could post a dev version with this alternative start up - where the partial product values are on ('A').

**Comment by kathy-phet** [comment]
> How old are your nieces?

They were 11, in 5th grade but taking 6th grade math.

**Comment by amanda-phet** [comment]
@jonathanolson are you able to make this change and publish a dev version by Tuesday? (I'm interviewing the 3rd graders on Monday and Tuesday so I would like to compare the two of them on this feature.)

**Comment by jonathanolson** [comment]
Applied changes, will deploy dev versions and post here.

**Comment by jonathanolson** [comment]
Deployed:

- https://www.colorado.edu/physics/phet/dev/html/area-model-algebra/1.0.0-dev.5/phet/area-model-algebra_en_phet.html
- https://www.colorado.edu/physics/phet/dev/html/area-model-introduction/1.0.0-dev.7/phet/area-model-introduction_en_phet.html
- https://www.colorado.edu/physics/phet/dev/html/area-model-multiplication/1.0.0-dev.21/phet/area-model-multiplication_en_phet.html

(the decimals sim was unaffected by this change).

**Comment by amanda-phet** [comment]
I didn't notice a difference between the two students when it came to partial products being visible or not. They both played with that control in approximately the same time frame whether they started as visible or not. 

The reason I prefer to have them hidden at first is to allow students to spend some time understanding the partition line and how it breaks up the side lengths of the area model before getting that extra level of information. But since all students explored the visibility radio buttons, I could go either way.

**Comment by amanda-phet** [comment]
@kathy-phet it is your call.

**Comment by jonathanolson** [comment]
Assigning myself, as I'll want to make a code change depending on what the decision is.

**Comment by amanda-phet** [comment]
@kathy-phet and I discussed 2/20/18 and decided to leave partial products hidden by default. So, let's undo this change.

**Comment by jonathanolson** [comment]
Reverted. Anything else to do here?

**Comment by amanda-phet** [comment]
I just checked on phettest and it looks like it is working. Thanks.
