### ISSUE TITLE
Dimensions scaling

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/area-model-common#91]
It seems like the dimensions are scaling down in size as they get large, but the baseline of the text is moving up. However the total area of model maintains the same baseline. Dimensions should do what the total area is doing.

![screen shot 2018-02-27 at 2 20 08 pm](https://user-images.githubusercontent.com/7852916/36755420-68ca088c-1bc9-11e8-808c-2514b5807438.png)

I'm not sure if this affects other screens because I don't see dimensions scaling much on the Generic screen, but it's very obvious on the Variables screen.

**Comment by jonathanolson** [comment]
Implemented:
![area-model-dimensions](https://user-images.githubusercontent.com/480878/37075406-e34ffc36-218e-11e8-941a-1ad801d6b8a6.PNG)

There are two minor alignment issues that bug me:

If one side has an exponent and the other doesn't (variables screen), the two sides have a different text baseline (the bottoms aren't aligned):
![area-model-align-2](https://user-images.githubusercontent.com/480878/37075759-89f19a80-2190-11e8-8353-e601d95232cf.PNG)

The box isn't aligned with the parenthesis (this may be solvable with looking up a unicode character that's a box that is letter-sized, but otherwise we can't always get the font data EASILY - I can technically have it determine the proper parenthesis size and layout correctly if desired, or investigate a unicode char):
![area-model-align-1](https://user-images.githubusercontent.com/480878/37075751-81ed59be-2190-11e8-84e9-9136fe86963e.PNG)

Thoughts?

**Comment by amanda-phet** [comment]
>If one side has an exponent and the other doesn't (variables screen), the two sides have a different text baseline (the bottoms aren't aligned): 

I agree, this is annoying. Is there a way to fix it? Ideally these are bottom-aligned. 

>The box isn't aligned with the parenthesis (this may be solvable with looking up a unicode character that's a box that is letter-sized

Again, I totally agree. I don't know if I have solutions for these problems, though.. but let me know what I can do to help.

**Comment by jonathanolson** [comment]
Reworked the vertical alignment in a lot of ways, should handle both issues I mentioned:

![area-model-dimensions-a](https://user-images.githubusercontent.com/480878/37437380-80fd4f32-27b2-11e8-858f-f59db4ae8f4b.PNG)
![area-model-dimensions-b](https://user-images.githubusercontent.com/480878/37437387-83b94bea-27b2-11e8-9ea0-65547f72c50d.PNG)

It manages to look up the exact height of the parentheses to align the box, which may slow the sim's startup time a bit more.

Then I saw the exact same annoyance in the partial products:
![area-model-partial-product-align](https://user-images.githubusercontent.com/480878/37437429-d18f3ae6-27b2-11e8-82f2-b4e9289aecd8.PNG)

I'm leaving this open so I can fix that also.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by amanda-phet** [comment]
I see the alignment a little bit off when one component is x^2, but it's not huge

<img width="296" alt="screen shot 2018-03-15 at 11 54 15 am" src="https://user-images.githubusercontent.com/7852916/37481568-b4f1caa8-2847-11e8-975b-069aca33570b.png">

What do you think  @jonathanolson ? I am OK leaving it as-is because it's pretty minor, but since you just worked on it you might know why this is happening.
