### ISSUE TITLE
Accordion Box consistency

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#92]
I'm temporarily removing the "hack" that made the Calculation accordion box (Partition screen on Introduction sim) collapsible by clicking anywhere. It would be good to have a discussion for whether this type of feature is necessary. Showing the title while expanded would make the "top" part still clickable, and that may be an option.

**Comment by jonathanolson** [comment]
Pushed master. @amanda-phet, can you try out the Calculation accordion box behavior, and see if it is acceptable?

**Comment by amanda-phet** [comment]
Why are we removing this feature? I thought we agreed it is nice to be able to click anywhere on the top to expand, and if you wanted to immediately close it you could click where your cursor already is. Is this considered unusual UX behavior?

**Comment by ariel-phet** [comment]
A11y concerns were raised for removing the title. Since the title fits, it seems like more standard UX behavior (so yes it is considered unusual). There was also pushback that @jonathanolson had introduced a fairly horrible hack into the code to accomplish the feature. 

So you should be able to click anywhere on the button or title text, which is consistent with the interaction with a checkbox for instance.

**Comment by amanda-phet** [comment]
I'm confused now.. are you suggesting we add in the title when this box is expanded? That's not what @jonathanolson did here. 

Sounds like there was a discussion about this accordion box and I'm missing some context. If we want to include the title, we need to make the panel considerably taller (there is space) because the calculations need a lot of extra padding to keep them easy to interpret. 

![screen shot 2018-03-01 at 1 56 19 pm](https://user-images.githubusercontent.com/7852916/36869269-761c0cac-1d58-11e8-904f-f82616fb0cde.png)

**Comment by ariel-phet** [comment]
@amanda-phet yes...my impression was the @jonathanolson added in the title when expanded

**Comment by ariel-phet** [comment]
@jonathanolson did this in master in area model introduction. Maybe we are talking about two different use cases in two different sims? I will try to catch you after meeting

**Comment by amanda-phet** [comment]
The first commit didn't include the title, and the second one did. So it is there now. 

@jonathanolson we could pixel polish this a bit but it is working.

**Comment by amanda-phet** [comment]
We can't actually move the panel up as I'd hoped, so I think we will just live with it how it is.
